import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Stethoscope, Scan, MessageSquare, MapPin, Calendar, Mic, ArrowRight, Leaf, Heart, ShieldCheck, Upload, Search, Pill, Users } from 'lucide-react';
import Navbar from '@/components/Navbar';

const features = [
  { icon: Scan, title: 'Image-Based Disease Detection', desc: 'Upload photos of your animal and get instant AI-powered disease identification.' },
  { icon: Pill, title: 'AI Remedy Suggestions', desc: 'Receive first aid instructions and precautions generated by AI.' },
  { icon: MapPin, title: 'Nearby Vet Recommendation', desc: 'Find trusted veterinarians in your area filtered by location.' },
  { icon: Calendar, title: 'Appointment Booking', desc: 'Book appointments with vets and track their status in real-time.' },
  { icon: Mic, title: 'Voice-to-Text Support', desc: 'Describe symptoms using your voice for easy and fast input.' },
  { icon: MessageSquare, title: 'ML-Based Chatbot', desc: 'Get instant answers to common animal health questions.' },
];

const steps = [
  { num: '01', icon: Upload, title: 'Upload Animal Image', desc: 'Take a clear photo of the affected area and upload it.' },
  { num: '02', icon: Search, title: 'Get Disease Detection', desc: 'Our AI analyzes the image and identifies the disease.' },
  { num: '03', icon: Pill, title: 'View AI-Based Remedy', desc: 'Receive actionable first aid and treatment suggestions.' },
  { num: '04', icon: Users, title: 'Book Vet Appointment', desc: 'Connect with a nearby vet and schedule a visit.' },
];

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero */}
      <section id="hero" className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-secondary/5 to-highlight/10" />
        <div className="container mx-auto px-4 py-20 md:py-32 relative">
          <div className="max-w-3xl mx-auto text-center animate-fade-in">
            <div className="inline-flex items-center gap-2 bg-primary/10 rounded-full px-4 py-1.5 mb-6">
              <Leaf className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium text-primary">AI-Powered Veterinary Care</span>
            </div>
            <h1 className="font-heading text-4xl md:text-6xl font-extrabold leading-tight mb-6 text-foreground">
              AI-Powered Animal Health
              <span className="text-primary"> Assistant</span> for Farmers
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
              Detect diseases. Get remedies. Connect with trusted vets — all from your phone.
            </p>
            <div className="flex flex-wrap gap-4 justify-center">
              <Link to="/signup">
                <Button size="lg" className="gap-2 text-base px-8">
                  Get Started <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
              <a href="#about">
                <Button size="lg" variant="outline" className="text-base px-8">Learn More</Button>
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* About */}
      <section id="about" className="py-20 bg-card">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="font-heading text-3xl md:text-4xl font-bold mb-6">Empowering Rural Farmers with AI</h2>
            <p className="text-muted-foreground text-lg leading-relaxed">
              Many farmers in rural areas lack access to timely veterinary care. Our AI-based system bridges this gap by providing instant disease detection from animal images, AI-generated remedies, and direct connections to nearby veterinarians — all designed to be simple and accessible.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12">
              {[
                { icon: ShieldCheck, label: 'Trusted AI Detection', value: '92%+ Accuracy' },
                { icon: Heart, label: 'Animals Helped', value: '10,000+' },
                { icon: Stethoscope, label: 'Verified Vets', value: '500+' },
              ].map((stat) => (
                <div key={stat.label} className="bg-background rounded-xl p-6 shadow-sm border">
                  <stat.icon className="h-8 w-8 text-primary mx-auto mb-3" />
                  <div className="font-heading text-2xl font-bold text-foreground">{stat.value}</div>
                  <div className="text-sm text-muted-foreground">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-4">Key Features</h2>
          <p className="text-center text-muted-foreground mb-12 max-w-xl mx-auto">Everything you need to keep your animals healthy and productive.</p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f) => (
              <div key={f.title} className="bg-card rounded-xl p-6 border shadow-sm hover:shadow-md transition-shadow group">
                <div className="bg-primary/10 rounded-lg p-3 w-fit mb-4 group-hover:bg-primary/20 transition-colors">
                  <f.icon className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-heading font-bold text-lg mb-2">{f.title}</h3>
                <p className="text-muted-foreground text-sm">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 bg-card">
        <div className="container mx-auto px-4">
          <h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-4">How It Works</h2>
          <p className="text-center text-muted-foreground mb-12">Simple 4-step process to get veterinary assistance.</p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {steps.map((s, i) => (
              <div key={s.num} className="relative bg-background rounded-xl p-6 border text-center" style={{ animationDelay: `${i * 0.1}s` }}>
                <div className="text-4xl font-heading font-extrabold text-primary/20 mb-2">{s.num}</div>
                <div className="bg-primary/10 rounded-full p-3 w-fit mx-auto mb-4">
                  <s.icon className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-heading font-bold mb-2">{s.title}</h3>
                <p className="text-sm text-muted-foreground">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-foreground text-background py-12">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <div className="bg-primary rounded-full p-1.5">
                  <Leaf className="h-5 w-5 text-primary-foreground" />
                </div>
                <span className="font-heading font-bold text-xl">VetAI</span>
              </div>
              <p className="text-sm opacity-70">AI-powered animal health assistant helping farmers across India.</p>
            </div>
            <div>
              <h4 className="font-heading font-bold mb-3">Quick Links</h4>
              <div className="space-y-2 text-sm opacity-70">
                <a href="/#features" className="block hover:opacity-100">Features</a>
                <a href="/#about" className="block hover:opacity-100">About</a>
                <Link to="/login" className="block hover:opacity-100">Login</Link>
                <Link to="/signup" className="block hover:opacity-100">Sign Up</Link>
              </div>
            </div>
            <div>
              <h4 className="font-heading font-bold mb-3">Demo Credentials</h4>
              <div className="text-sm opacity-70 space-y-2">
                <p><strong>Farmer:</strong> farmer@demo.com / 123456</p>
                <p><strong>Doctor:</strong> doctor@demo.com / 123456</p>
              </div>
            </div>
          </div>
          <div className="border-t border-background/20 mt-8 pt-6 text-center text-sm opacity-50">
            © 2026 VetAI. All rights reserved.
          </div>
        </div>
      </footer>

    </div>
  );
};

export default LandingPage;
